/** UI copy in both locales. Investor-facing wording follows BR-013: no guarantees. */
export const STRINGS = {
  // ── brand & navigation
  brand:            { ar: 'حِصّة', en: 'Hissa' },
  brandTagline:     { ar: 'استثمار في مشاريع عُمانية قائمة', en: 'Investing in established Omani projects' },
  navOpportunities: { ar: 'الفرص', en: 'Opportunities' },
  navHowItWorks:    { ar: 'كيف تعمل', en: 'How it works' },
  navRisks:         { ar: 'المخاطر', en: 'Risks' },
  navFees:          { ar: 'الرسوم', en: 'Fees' },
  navFaq:           { ar: 'الأسئلة', en: 'FAQ' },
  navPortfolio:     { ar: 'محفظتي', en: 'Portfolio' },
  navProjectPortal: { ar: 'بوابة المشروع', en: 'Project portal' },
  navConsole:       { ar: 'لوحة التشغيل', en: 'Operations' },
  navComplaints:    { ar: 'الشكاوى', en: 'Complaints' },
  navNotifications: { ar: 'الإشعارات', en: 'Notifications' },
  navProfile:       { ar: 'حسابي', en: 'Account' },
  signIn:           { ar: 'تسجيل الدخول', en: 'Sign in' },
  signOut:          { ar: 'تسجيل الخروج', en: 'Sign out' },
  register:         { ar: 'إنشاء حساب', en: 'Create account' },
  languageToggle:   { ar: 'English', en: 'العربية' },

  // ── generic
  loading:      { ar: 'جارٍ التحميل…', en: 'Loading…' },
  error:        { ar: 'حدث خطأ', en: 'Something went wrong' },
  retry:        { ar: 'إعادة المحاولة', en: 'Try again' },
  save:         { ar: 'حفظ', en: 'Save' },
  submit:       { ar: 'إرسال', en: 'Submit' },
  cancel:       { ar: 'إلغاء', en: 'Cancel' },
  confirm:      { ar: 'تأكيد', en: 'Confirm' },
  approve:      { ar: 'اعتماد', en: 'Approve' },
  reject:       { ar: 'رفض', en: 'Reject' },
  continueText: { ar: 'متابعة', en: 'Continue' },
  back:         { ar: 'رجوع', en: 'Back' },
  close:        { ar: 'إغلاق', en: 'Close' },
  search:       { ar: 'بحث', en: 'Search' },
  all:          { ar: 'الكل', en: 'All' },
  none:         { ar: 'لا يوجد', en: 'None' },
  empty:        { ar: 'لا توجد عناصر لعرضها', en: 'Nothing to show' },
  required:     { ar: 'حقل مطلوب', en: 'Required' },
  optional:     { ar: 'اختياري', en: 'Optional' },
  amount:       { ar: 'المبلغ', en: 'Amount' },
  status:       { ar: 'الحالة', en: 'Status' },
  date:         { ar: 'التاريخ', en: 'Date' },
  reference:    { ar: 'المرجع', en: 'Reference' },
  reason:       { ar: 'السبب', en: 'Reason' },
  details:      { ar: 'التفاصيل', en: 'Details' },
  actions:      { ar: 'إجراءات', en: 'Actions' },
  viewDetails:  { ar: 'عرض التفاصيل', en: 'View details' },

  // ── home
  heroTitle:    { ar: 'مشروع محدد. أموال منفصلة. متابعة موثقة.',
                  en: 'A specific project. Segregated funds. Documented follow-up.' },
  heroBody:     { ar: 'تحوّل حِصّة توسعًا تشغيليًا محددًا — فرعًا جديدًا أو أصلًا إنتاجيًا — إلى فرصة مستقلة ذات استخدام أموال واضح وإفصاح موحد ومتابعة بعد التمويل.',
                  en: 'Hissa turns a specific operational expansion — a new branch or a production asset — into a standalone opportunity with a clear use of funds, a standard disclosure, and post-funding monitoring.' },
  heroCta:      { ar: 'استعرض الفرص', en: 'Browse opportunities' },
  heroSecondary:{ ar: 'قدّم مشروعك', en: 'Submit your project' },
  statFunded:   { ar: 'فرص مموّلة', en: 'Funded opportunities' },
  statAmount:   { ar: 'إجمالي التمويل', en: 'Total funded' },
  statLive:     { ar: 'فرص مفتوحة', en: 'Live opportunities' },
  statInvestors:{ ar: 'مستثمرون', en: 'Investors' },
  statsNote:    { ar: 'الأرقام تعكس سجلات المنصة ولا تمثل توقعًا لأداء مستقبلي.',
                  en: 'Figures reflect platform records and do not indicate future performance.' },

  // ── risk (BR-013)
  riskBanner:   { ar: 'قد تخسر كامل المبلغ المستثمر. لا ضمان للعائد أو لرأس المال، ولا توجد سوق ثانوية.',
                  en: 'You may lose your entire investment. No return or capital is guaranteed, and there is no secondary market.' },
  riskTitle:    { ar: 'المخاطر قبل القرار', en: 'Risks before you decide' },
  regulatoryNote:{ ar: 'تعمل حِصّة من خلال مشغل تمويل جماعي مرخّص في سلطنة عُمان. جمع الأموال وتنفيذ الاستثمار يتم عبر الشريك المرخّص، ولا تحتفظ حِصّة بأموال المستثمرين في حسابها التشغيلي.',
                  en: 'Hissa operates through a licensed crowdfunding operator in the Sultanate of Oman. Funds are collected and investments executed by the licensed partner; Hissa does not hold investor money in its operating account.' },

  // ── marketplace
  marketplaceTitle: { ar: 'الفرص الاستثمارية', en: 'Investment opportunities' },
  filterSector:     { ar: 'القطاع', en: 'Sector' },
  filterGovernorate:{ ar: 'المحافظة', en: 'Governorate' },
  filterStatus:     { ar: 'الحالة', en: 'Status' },
  sortBy:           { ar: 'الترتيب', en: 'Sort by' },
  sortNewest:       { ar: 'الأحدث', en: 'Newest' },
  sortClosingSoon:  { ar: 'الأقرب إغلاقًا', en: 'Closing soon' },
  sortProgress:     { ar: 'حجم التمويل', en: 'Funding size' },
  raised:           { ar: 'المجمّع', en: 'Raised' },
  target:           { ar: 'الهدف', en: 'Target' },
  minimumTicket:    { ar: 'الحد الأدنى', en: 'Minimum' },
  daysRemaining:    { ar: 'يومًا متبقيًا', en: 'days left' },
  investorCount:    { ar: 'مستثمر', en: 'investors' },
  tenor:            { ar: 'المدة', en: 'Term' },
  months:           { ar: 'شهرًا', en: 'months' },

  // ── pool detail
  tabOverview:   { ar: 'نظرة عامة', en: 'Overview' },
  tabFinancials: { ar: 'البيانات المالية', en: 'Financials' },
  tabRights:     { ar: 'الحقوق والخروج', en: 'Rights & exit' },
  tabRisks:      { ar: 'المخاطر', en: 'Risks' },
  tabDataRoom:   { ar: 'الأدلة', en: 'Data room' },
  tabQa:         { ar: 'أسئلة وأجوبة', en: 'Q&A' },
  useOfFunds:    { ar: 'استخدام الأموال', en: 'Use of funds' },
  scenarios:     { ar: 'السيناريوهات', en: 'Scenarios' },
  scenarioConservative: { ar: 'متحفظ', en: 'Conservative' },
  scenarioBase:  { ar: 'أساسي', en: 'Base' },
  scenarioOptimistic:   { ar: 'متفائل', en: 'Optimistic' },
  scenarioNote:  { ar: 'السيناريوهات توقعات مبنية على افتراضات قد لا تتحقق، وليست وعدًا بعائد.',
                   en: 'Scenarios are projections based on assumptions that may not hold. They are not a promise of return.' },
  historicalRevenue: { ar: 'الإيرادات التاريخية', en: 'Historical revenue' },
  disclosureVersion: { ar: 'نسخة الإفصاح', en: 'Disclosure version' },
  askQuestion:   { ar: 'اطرح سؤالًا', en: 'Ask a question' },
  questionPending:{ ar: 'يُنشر السؤال والجواب بعد مراجعة الفريق المخول.',
                   en: 'Questions and answers are published after review by the authorised team.' },
  dataRoomLocked:{ ar: 'بعض الملفات متاحة للمستثمرين المؤهلين بعد اكتمال التحقق من الهوية.',
                   en: 'Some files are available to verified investors once identity verification is complete.' },
  investNow:     { ar: 'استثمر في هذه الفرصة', en: 'Invest in this opportunity' },

  // ── checkout
  checkoutTitle:    { ar: 'إتمام الاستثمار', en: 'Complete your investment' },
  checkoutAmount:   { ar: 'مبلغ الاستثمار', en: 'Investment amount' },
  availableToYou:   { ar: 'المتاح لك', en: 'Available to you' },
  units:            { ar: 'الوحدات', en: 'Units' },
  ownershipShare:   { ar: 'نسبة الملكية', en: 'Ownership share' },
  feesSummary:      { ar: 'ملخص الرسوم', en: 'Fee summary' },
  investorFee:      { ar: 'رسوم على المستثمر', en: 'Investor fee' },
  totalToPay:       { ar: 'الإجمالي', en: 'Total' },
  acknowledgements: { ar: 'الإقرارات', en: 'Acknowledgements' },
  acknowledgeAll:   { ar: 'يلزم الإقرار بجميع البنود قبل المتابعة.',
                      en: 'All acknowledgements are required before you can continue.' },
  proceedToPayment: { ar: 'المتابعة للدفع عبر الشريك المرخّص', en: 'Continue to payment with the licensed partner' },
  paymentNote:      { ar: 'يتم الدفع وحفظ الأموال لدى الشريك المرخّص في حساب ضمان منفصل. لا تجمع حِصّة بيانات بطاقتك.',
                      en: 'Payment and custody sit with the licensed partner in a segregated escrow account. Hissa never collects your card details.' },
  orderPending:     { ar: 'التزامك قيد التأكيد لدى الشريك. لا يعني التأخير فشل العملية.',
                      en: 'Your commitment is being confirmed by the partner. A delay does not mean the payment failed.' },
  orderConfirmed:   { ar: 'تم تأكيد التزامك الاستثماري.', en: 'Your commitment is confirmed.' },
  downloadReceipt:  { ar: 'تنزيل الإيصال', en: 'Download receipt' },

  // ── eligibility blocks
  eligibilityTitle: { ar: 'متطلبات قبل الاستثمار', en: 'Before you can invest' },
  completeKyc:      { ar: 'إكمال التحقق من الهوية', en: 'Complete identity verification' },
  completeSuitability: { ar: 'إكمال اختبار الملاءمة', en: 'Complete the suitability assessment' },
  completeConsents: { ar: 'الموافقة على الشروط وإفصاح المخاطر والخصوصية', en: 'Accept the terms, risk disclosure and privacy policy' },

  // ── portfolio
  portfolioTitle:   { ar: 'محفظتي', en: 'My portfolio' },
  invested:         { ar: 'المستثمر', en: 'Invested' },
  distributed:      { ar: 'التوزيعات المستلمة', en: 'Distributions received' },
  pendingCommitments:{ ar: 'التزامات قيد التأكيد', en: 'Pending commitments' },
  activePools:      { ar: 'فرص قائمة', en: 'Active pools' },
  valuationNote:    { ar: 'تعرض القيم الاسمية للاستثمار والتوزيعات المحققة فقط. لا تقدم المنصة قيمة سوقية للحصص.',
                      en: 'Only nominal invested amounts and realised distributions are shown. The platform does not provide a market value for holdings.' },
  statements:       { ar: 'كشوف الحساب', en: 'Statements' },
  reports:          { ar: 'التقارير', en: 'Reports' },
  votes:            { ar: 'التصويت', en: 'Votes' },

  // ── identity
  fullName:      { ar: 'الاسم الكامل', en: 'Full name' },
  email:         { ar: 'البريد الإلكتروني', en: 'Email' },
  phone:         { ar: 'رقم الهاتف', en: 'Phone number' },
  password:      { ar: 'كلمة المرور', en: 'Password' },
  otpCode:       { ar: 'رمز التحقق', en: 'Verification code' },
  verifyContact: { ar: 'تأكيد وسيلة الاتصال', en: 'Verify your contact channel' },
  mfaTitle:      { ar: 'التحقق بخطوتين', en: 'Two-factor verification' },
  accountTypeInvestor: { ar: 'مستثمر', en: 'Investor' },
  accountTypeOwner:    { ar: 'صاحب مشروع', en: 'Project owner' },
  classification:{ ar: 'تصنيف المستثمر', en: 'Investor classification' },
  kycStatus:     { ar: 'حالة التحقق', en: 'Verification status' },

  // ── project portal
  ownerPortalTitle: { ar: 'بوابة المشروع', en: 'Project portal' },
  newApplication:   { ar: 'طلب تمويل جديد', en: 'New funding application' },
  applicationStatus:{ ar: 'حالة الطلب', en: 'Application status' },
  documents:        { ar: 'المستندات', en: 'Documents' },
  tasks:            { ar: 'المهام', en: 'Tasks' },
  infoRequests:     { ar: 'طلبات الاستكمال', en: 'Information requests' },
  completeness:     { ar: 'اكتمال الطلب', en: 'Application completeness' },
  missingItems:     { ar: 'العناصر الناقصة', en: 'Missing items' },
  submitApplication:{ ar: 'إرسال الطلب', en: 'Submit application' },

  // ── operations console
  consoleTitle:    { ar: 'لوحة التشغيل', en: 'Operations console' },
  queueKyc:        { ar: 'مراجعة الهوية', en: 'Identity review' },
  queueDd:         { ar: 'العناية الواجبة', en: 'Due diligence' },
  queueCommittee:  { ar: 'لجنة الاستثمار', en: 'Investment committee' },
  queueFunds:      { ar: 'اعتمادات مالية', en: 'Funds approvals' },
  queueBreaks:     { ar: 'فروقات المطابقة', en: 'Reconciliation breaks' },
  queueCases:      { ar: 'حالات متأخرة', en: 'Overdue cases' },
  queueReports:    { ar: 'تقارير متأخرة', en: 'Late reports' },
  auditLog:        { ar: 'سجل التدقيق', en: 'Audit log' },
  settingsTitle:   { ar: 'الإعدادات', en: 'Settings' },
  exportsTitle:    { ar: 'التقارير والتصدير', en: 'Reports & exports' },
  dualControlNote: { ar: 'لا يمكن لمن أنشأ الطلب اعتماده. يلزم اعتماد مستخدم ثانٍ مخوّل.',
                     en: 'The user who created a request cannot approve it. A second authorised user must approve.' },

  // ── complaints
  complaintsTitle: { ar: 'الشكاوى والدعم', en: 'Complaints & support' },
  newComplaint:    { ar: 'شكوى جديدة', en: 'New complaint' },
  complaintCategory:{ ar: 'التصنيف', en: 'Category' },
  complaintSubject: { ar: 'الموضوع', en: 'Subject' },
  complaintBody:   { ar: 'التفاصيل', en: 'Details' },
  slaDue:          { ar: 'الموعد المستهدف', en: 'Target response' },

  // ── footer
  footerRegulator: { ar: 'الإشراف التنظيمي: هيئة الخدمات المالية — قواعد منصات التمويل الجماعي (القرار E/153/2021).',
                     en: 'Regulatory oversight: Financial Services Authority — Crowdfunding Platform Rules (Decision E/153/2021).' },
  footerData:      { ar: 'تُعالج البيانات الشخصية وفق قانون حماية البيانات الشخصية (المرسوم السلطاني 6/2022) ولائحته التنفيذية.',
                     en: 'Personal data is processed under the Personal Data Protection Law (Royal Decree 6/2022) and its executive regulation.' },
  footerNotAdvice: { ar: 'المحتوى على هذه المنصة لا يشكل نصيحة استثمارية أو ضريبية أو قانونية.',
                     en: 'Nothing on this platform constitutes investment, tax or legal advice.' },
} as const;

export type StringKey = keyof typeof STRINGS;
